### ISSUE TITLE
iframe-originating pop-ups rules are not remembered / enforced

### ISSUE THREAD

**Issue by bitoolean** [Eskander/ultra-popup-blocker#9]
optional, safe-to-ignore below rant behind how I encountered the issue:

Hi!

I was going to provide more details on this issue and tell you how much I appreciate you rewriting Ultra Popup Blocker but I haven't gotten the time. I haven't seen the new changes in action yet.

I encountered this just before you started writing this new version. I think Ultra Popup Blocker did detect the popup, but failed to remember not to block it, and disabling Ultra Popup Blocker either on the current tab or even globally had no effect even. It was pretty annoying, given how this was a website I was ordering something off of, and this was the payment processor pop-up that was being blocked - after investigation, I realized it must've been because the pop-up originated from code within an IFRAME on that payment page (the page was still on the store website, and the IFRAME must've been the payment provider's). Luckily, having to refresh a few times after no option worked, the order / money only went through once (I was only buying pens anyway), but I had to disable Ultra Popup Blocker in the browser options and probably restarted it.

I know IFRAMEs are a relic, but apparently people still use them. In this case, CartridgePeople. But the bigger issue is UPB might be ignoring an entire category of pop-ups then.

I'm excited to see the recent redesign in action!
Thank you for sharing this work with us!

**Comment by Eskander** [comment]
What GM extension are you using?
I use Tampermonkey, which fires a separate session for every iframe in a webpage, ensuring that UPB captures all popup initiation attempts. I suppose it works the same for other userscript managers, but who knows?

Also, in the new version of UPB, I made it that permissions are granted to the top website (eg. cartridgepeople.com in your case) instead of per popup on the same website (cause it was annoying in practice), so the problem you encountered supposedly is fixed as in: trusting the store website would trust its payments popups as well.

When you try the new version it would be helpful if you can provide feedback.

---
On a separate matter, don't refresh webpages that contain forms (payment/other), weird things **will** happen.
